import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case english
    case chinese

    var id: String { rawValue }

    var title: String {
        switch self {
        case .english: "English"
        case .chinese: "中文"
        }
    }
}

enum L {
    static func text(_ key: String, _ language: AppLanguage) -> String {
        switch language {
        case .english:
            english[key] ?? key
        case .chinese:
            chinese[key] ?? english[key] ?? key
        }
    }

    private static let english: [String: String] = [
        "overview": "Overview",
        "audit": "Audit",
        "statistics": "Statistics",
        "settings": "Settings",
        "quit_app": "Quit",
        "refresh": "Refresh",
        "five_hour": "5-hour",
        "weekly": "Weekly",
        "remaining": "remaining",
        "tokens": "Tokens",
        "cost": "Cost",
        "service_mix": "Service mix",
        "model_detail": "Model detail",
        "range": "Range",
        "data_sources": "Data sources",
        "security": "Security",
        "refresh_interval": "Refresh interval",
        "interval": "Interval:",
        "login_item": "Open at login",
        "menu_item": "Menu bar item",
        "language": "Language",
        "active_account_windows": "Current account 5H/WK",
        "lowest_remaining": "Lowest remaining",
        "total_tokens": "Total tokens",
        "codex_only": "Codex remaining",
        "custom_range": "Custom range",
        "empty_cost": "Cost requires model pricing or an authorized Admin API source.",
        "claude_unavailable": "Claude Code source unavailable",
        "usage_statistics": "Usage",
        "service": "Service",
        "all": "All",
        "openai": "OpenAI",
        "anthropic": "Anthropic",
        "view": "View",
        "timeline": "Timeline",
        "details": "Details",
        "total_cost": "Total cost",
        "total": "Total",
        "compared_to_yesterday": "vs yesterday",
        "openai_overview": "OpenAI overview",
        "share_of_total_cost": "share of total cost",
        "auto_update_status": "Auto-updates every minute",
        "secure_status": "Data security protected",
        "daily_usage": "Daily usage",
        "tokens_ten_thousands": "Token (10k)",
        "cost_usd": "Cost (USD)",
        "current_limits": "Current limits",
        "by_service": "By service",
        "by_model": "By model",
        "no_usage_events": "No usage events",
        "no_usage_data": "No usage data",
        "no_quota_windows": "No quota windows",
        "no_model_data": "No model data",
        "loading_accounts": "Loading accounts",
        "loading_account_info": "Loading account information",
        "loading_account_info_subtitle": "Reading local Codex and Claude Code accounts",
        "accounts_loaded": "accounts loaded",
        "share": "share",
        "input_abbrev": "In",
        "output_abbrev": "Out",
        "reset_time_unknown": "Reset time unknown",
        "reset": "Reset",
        "resets": "Resets",
        "reset_available": "reset available",
        "resets_available": "resets available",
        "expires": "expires",
        "resets_after": "until reset",
        "expiry_dates": "Expiry dates",
        "expiry_dates_help": "Opt in to a read-only reset-credit expiry check using local Codex auth",
        "next_expiry": "Next expiry",
        "five_hour_left": "5H left",
        "weekly_left": "Weekly left",
        "expiry_watch": "Expiry watch",
        "current_windows": "Current windows",
        "reset_intro": "Banked credits, expiry warnings, and the spend call.",
        "enable_expiry_dates": "Turn on Expiry dates to fetch detailed reset-credit expiry times.",
        "no_detailed_expiry_dates": "No detailed expiry dates returned yet.",
        "no_banked_resets": "No banked resets found.",
        "expiry_date_unavailable": "Expiry date unavailable",
        "unknown": "Unknown",
        "expired": "Expired",
        "today": "Today",
        "soon": "Soon",
        "this_week": "This week",
        "hide_full_text": "Hide full text",
        "show_full_text": "Show full text",
        "resize_popover": "Resize popover",
        "resize_current_limits": "Resize Current limits",
        "stacked_usage_bars": "Stacked usage bars",
        "last_activity": "Last activity",
        "account_type": "Account type",
        "workspace": "Workspace",
        "workspaces": "Workspaces",
        "more": "more",
        "accounts": "Accounts",
        "accounts_settings_subtitle": "Automatically detects local accounts; no placeholder is shown without a safe data source.",
        "available": "Available",
        "no_safe_local_source": "No safe local source",
        "menu_bar": "Menu bar",
        "menu_bar_settings_subtitle": "Control what the menu bar status item displays.",
        "display_value": "Display value",
        "display_value_subtitle": "Choose the value next to the icon.",
        "refresh_settings_subtitle": "Background polling checks the Codex usage API, then reads local usage data.",
        "refresh_interval_subtitle": "Applies to Codex usage API sync and local data refresh.",
        "quota_reset_notifications": "Quota reset notifications",
        "quota_reset_notifications_subtitle": "Show a desktop notification when 5-hour or weekly quota refreshes.",
        "open_at_login_subtitle": "Open AgentBar at login.",
        "general": "General",
        "general_settings_subtitle": "Language and app behavior.",
        "language_subtitle": "Interface language.",
        "current_account": "Current account",
        "current": "Current",
        "account_forced_logout_warning": "OpenAI returned 401. Log in to this account again.",
        "account_unreadable_reset_warning": "Reset data is unreadable. Log in to this account again.",
        "no_cost_data": "No cost data",
        "usage_windows": "Usage windows",
        "team": "Team"
        ,"login_accounts": "Login accounts",
        "login_accounts_subtitle": "Open the provider CLI login flow in Terminal, then refresh AgentBar.",
        "login_codex": "Login Codex",
        "login_claude": "Login Claude",
        "dark_theme": "Dark theme",
        "dark_theme_subtitle": "Use a dark app appearance instead of following the system.",
        "tone_color": "Tone color",
        "tone_color_subtitle": "Applies to selections, charts, bars, and quota progress.",
        "account_sort": "Account sorting",
        "account_sort_subtitle": "Controls account order in the popover and current limits.",
        "auto_codex_rotation": "Auto-switch Codex accounts",
        "auto_codex_rotation_subtitle": "When the current Codex account is low on 5-hour quota, switch to the best available account.",
        "codex_rotation_threshold": "Switch below",
        "codex_rotation_threshold_subtitle": "Remaining 5-hour quota that triggers automatic switching.",
        "use_account": "Use account",
        "login_account": "Log in",
        "remove_account": "Remove account",
        "remove_account_confirmation": "Remove this account from AgentBar and local Codex credentials. You can add it again by logging in.",
        "switching_account": "Switching account",
        "daily_usage_for": "Daily usage",
        "software_update": "Software update",
        "current_version": "Current version",
        "check_for_updates": "Check for updates",
        "install_and_restart": "Install and restart",
        "updates_daily_check": "AgentBar checks for updates automatically once per day.",
        "checking_for_updates": "Checking GitHub releases...",
        "app_up_to_date": "AgentBar is up to date.",
        "downloading_update": "Downloading %@...",
        "update_ready_to_install": "%@ is downloaded and ready to install.",
        "installing_update": "Installing %@ and restarting...",
        "update_check_failed": "Update failed: %@",
        "update_install_subtitle": "Install the downloaded update into /Applications.",
        "title": "Codex Usage Audit",
        "subtitle": "Reads local JSONL so token and credit spend is traceable.",
        "visible_calls": "Visible calls",
        "cached_input": "Cached input",
        "uncached_input": "Uncached input",
        "reasoning_output": "Reasoning output",
        "estimated_cost": "Estimated cost",
        "model_calls": "Model calls",
        "threads": "Threads",
        "calls": "calls",
        "calls_caption": "Showing filtered model calls. Click any row for source and token details.",
        "threads_caption": "Grouped by thread. Click a thread to expand its calls.",
        "time": "Time",
        "thread": "Thread",
        "duration": "Duration",
        "initiated": "Initiated",
        "model": "Model",
        "effort": "Effort",
        "cached": "Cached",
        "uncached": "Uncached",
        "output": "Output",
        "reasoning": "Reasoning",
        "unknown_thread": "Unknown thread",
        "call_investigator": "Call investigator",
        "show_source": "Show source",
        "last_call_input": "Last call input",
        "exact_from_callback": "Exact from callback",
        "fresh_context": "Fresh context",
        "assistant_output": "Assistant output",
        "configured_price": "Configured price",
        "source_line": "Source line",
        "source_file_line": "Source file and line",
        "privacy_note": "Exports store aggregate fields plus derived thread labels, not full prompts, replies, or tool output.",
        "exported": "Exported",
        "export_failed": "Export failed:",
        "page": "Page",
        "budgets": "Budgets",
        "budget_subtitle": "Set soft daily and weekly token/cost thresholds; AgentBar marks the menu bar when they are high.",
        "daily_token_budget": "Daily token budget",
        "weekly_token_budget": "Weekly token budget",
        "daily_cost_budget": "Daily cost budget",
        "weekly_cost_budget": "Weekly cost budget",
        "daily_token_budget_subtitle": "Set 0 to disable daily token alerts.",
        "weekly_token_budget_subtitle": "Set 0 to disable weekly token alerts.",
        "daily_cost_budget_subtitle": "Set 0 to disable daily cost alerts.",
        "weekly_cost_budget_subtitle": "Set 0 to disable weekly cost alerts.",
        "data_source_health": "Data source health",
        "top_usage": "Top usage",
        "session_drilldown": "Session drilldown",
        "year_activity": "Year activity",
        "account_health": "Account health",
        "account_health_subtitle": "Handle relogin, source issues, and stale accounts in one place.",
        "quota_capacity_history": "Quota capacity estimate",
        "quota_capacity_frequency": "Quota capacity sampling",
        "quota_capacity_frequency_subtitle": "Record estimated 5H and weekly capacity history on this cadence.",
        "quota_capacity_history_tooltip": "Estimates total token capacity for the 5H and weekly quota windows from recent samples, so you can track capacity trends and judge usage pace.",
        "use_it_or_lose_it": "Use it or lose it",
        "expires_today_message": "A banked reset expires today. If useful work is queued, spend it before it disappears.",
        "expiry_warning": "Expiry warning",
        "waiting_on_meters": "Waiting on meters",
        "waiting_on_meters_message": "Reset stash is visible, but Codex usage windows are not loaded yet.",
        "refresh_after_sign_in": "Refresh after Codex signs in",
        "no_reset_cushion": "No reset cushion",
        "no_reset_cushion_message": "No banked reset is available, so keep an eye on the weekly meter.",
        "let_5h_refill": "Let the 5H tank refill",
        "let_5h_refill_message": "Weekly room is still decent and the short window is close. Save the reset.",
        "deadline_call": "Deadline call",
        "deadline_call_message": "The short window is tight but weekly runway is healthy. Spend a reset only if real work is blocked.",
        "five_hour_nearly_empty": "5H nearly empty",
        "go_burn_tokens": "Go burn some tokens",
        "go_burn_tokens_message": "You have resets banked, weekly room is thin, and refresh is days away.",
        "green_light_with_brakes": "Green light, with brakes",
        "green_light_with_brakes_message": "If Codex blocks real work, spending a reset makes sense. Do not burn it just to tidy the meter.",
        "hold_that_reset": "Hold that reset",
        "hold_that_reset_message": "Weekly room is healthy and the next refresh is close.",
        "cruise_mode": "Cruise mode",
        "cruise_mode_message": "Keep working. Re-check before a big run.",
        "most_constrained": "Most constrained",
        "lowest_5h": "Lowest 5H",
        "lowest_weekly": "Lowest weekly",
        "quota_pressure": "Quota pressure",
        "view_details": "View details",
        "view_all_services": "View all services",
        "view_all_models": "View all models",
        "best_account": "Best account",
        "five_hour_exhausts": "5H may exhaust",
        "five_hour_healthy": "5H quota is healthy",
        "rotation_ready": "rotation will trigger",
        "rotation_standby": "rotation on standby",
        "quota_details": "Quota details",
        "active_account": "Active account",
        "recommended_account": "Recommended",
        "rotation": "Rotation",
        "will_trigger": "Will trigger",
        "standby": "Standby",
        "not_projected": "No exhaustion estimate",
        "quota_eta": "Quota ETA",
        "now": "now",
        "samples": "Samples",
        "waiting": "Waiting for two samples in the same quota window with token usage.",
        "sample_usage": "Sample usage",
        "rapid_burn": "Rapid usage burn",
        "sessions": "Sessions",
        "projects": "Projects",
        "days": "Days",
        "models": "Models",
        "latest": "Latest",
        "select_session": "Select a top session to inspect model usage.",
        "unknown_project": "Unknown project",
        "healthy": "No account or source issue needs action.",
        "login": "Login",
        "remove": "Remove account",
        "usage_anomalies": "Usage anomalies",
        "week": "Week",
        "no_sources": "No source status",
        "live": "Live",
        "issues": "Issues",
        "yes": "Yes",
        "no": "No"
    ]

    private static let chinese: [String: String] = [
        "overview": "概览",
        "audit": "审计",
        "statistics": "统计",
        "settings": "设置",
        "quit_app": "退出",
        "refresh": "刷新",
        "five_hour": "5 小时",
        "weekly": "本周",
        "remaining": "剩余",
        "tokens": "Token",
        "cost": "费用",
        "service_mix": "服务占比",
        "model_detail": "模型明细",
        "range": "范围",
        "data_sources": "数据源",
        "security": "安全",
        "refresh_interval": "刷新间隔",
        "interval": "区间：",
        "login_item": "开机启动",
        "menu_item": "菜单栏显示",
        "language": "语言",
        "active_account_windows": "当前账号 5 小时/本周",
        "lowest_remaining": "最低剩余额度",
        "total_tokens": "总 Token",
        "codex_only": "Codex 剩余",
        "custom_range": "自定义范围",
        "empty_cost": "费用需要模型价格或授权的 Admin API 数据源。",
        "claude_unavailable": "Claude Code 数据源不可用",
        "usage_statistics": "用量统计",
        "service": "服务",
        "all": "全部",
        "openai": "OpenAI",
        "anthropic": "Anthropic",
        "view": "视图",
        "timeline": "时间线",
        "details": "明细",
        "total_cost": "总花费",
        "total": "总计",
        "compared_to_yesterday": "较昨日",
        "openai_overview": "OpenAI 概览",
        "share_of_total_cost": "占总花费比例",
        "auto_update_status": "数据每分钟自动更新",
        "secure_status": "数据安全保护中",
        "daily_usage": "每日用量",
        "tokens_ten_thousands": "Token（万）",
        "cost_usd": "花费（美元）",
        "current_limits": "当前限额",
        "by_service": "按服务",
        "by_model": "按模型",
        "no_usage_events": "暂无用量事件",
        "no_usage_data": "暂无用量数据",
        "no_quota_windows": "暂无限额窗口",
        "no_model_data": "暂无模型数据",
        "loading_accounts": "正在加载账号",
        "loading_account_info": "正在加载账号信息",
        "loading_account_info_subtitle": "正在只读同步本机 Codex 与 Claude Code 账号",
        "accounts_loaded": "个账号已载入",
        "share": "占比",
        "input_abbrev": "入",
        "output_abbrev": "出",
        "reset_time_unknown": "重置时间未知",
        "reset": "重置",
        "resets": "重置",
        "reset_available": "次重置可用",
        "resets_available": "次重置可用",
        "expires": "过期",
        "resets_after": "后重置",
        "expiry_dates": "过期时间",
        "expiry_dates_help": "使用本机 Codex 授权只读检查重置额度过期时间",
        "next_expiry": "下次过期",
        "five_hour_left": "5 小时剩余",
        "weekly_left": "本周剩余",
        "expiry_watch": "过期监控",
        "current_windows": "当前窗口",
        "reset_intro": "查看已储备重置、过期提醒和使用建议。",
        "enable_expiry_dates": "开启过期时间后，会获取详细的重置额度过期时间。",
        "no_detailed_expiry_dates": "暂未返回详细过期时间。",
        "no_banked_resets": "暂无已储备重置。",
        "expiry_date_unavailable": "过期时间不可用",
        "unknown": "未知",
        "expired": "已过期",
        "today": "今天",
        "soon": "即将过期",
        "this_week": "本周",
        "hide_full_text": "收起全文",
        "show_full_text": "展开全文",
        "resize_popover": "调整弹窗大小",
        "resize_current_limits": "调整当前限额区域大小",
        "stacked_usage_bars": "堆叠用量柱状图",
        "last_activity": "最近活动",
        "account_type": "账号类型",
        "workspace": "工作区",
        "workspaces": "工作区",
        "more": "更多",
        "accounts": "账号",
        "accounts_settings_subtitle": "自动检测本机账号；无安全数据源时不显示占位账号。",
        "available": "可用",
        "no_safe_local_source": "无安全本地数据源",
        "menu_bar": "菜单栏",
        "menu_bar_settings_subtitle": "控制菜单栏状态项显示。",
        "display_value": "显示内容",
        "display_value_subtitle": "选择图标旁显示的数值。",
        "refresh_settings_subtitle": "后台轮询会先检查 Codex 用量 API，再读取本地用量数据。",
        "refresh_interval_subtitle": "应用于 Codex 用量 API 同步和本地数据刷新。",
        "quota_reset_notifications": "额度刷新通知",
        "quota_reset_notifications_subtitle": "5 小时或周额度刷新时显示桌面通知。",
        "open_at_login_subtitle": "登录时打开 AgentBar。",
        "general": "通用",
        "general_settings_subtitle": "语言和应用行为。",
        "language_subtitle": "界面语言。",
        "current_account": "当前账号",
        "current": "当前",
        "account_forced_logout_warning": "OpenAI 返回 401，请重新登录此账号。",
        "account_unreadable_reset_warning": "重置数据不可读，请重新登录此账号。",
        "no_cost_data": "暂无费用数据",
        "usage_windows": "用量窗口",
        "team": "团队",
        "login_accounts": "登录账号",
        "login_accounts_subtitle": "在终端打开服务商 CLI 登录流程，然后刷新 AgentBar。",
        "login_codex": "登录 Codex",
        "login_claude": "登录 Claude",
        "dark_theme": "深色主题",
        "dark_theme_subtitle": "使用深色应用外观，而不是跟随系统。",
        "tone_color": "色调颜色",
        "tone_color_subtitle": "应用到选中态、图表、柱状图和额度进度。",
        "account_sort": "账号排序",
        "account_sort_subtitle": "控制下拉菜单和当前限额里的账号顺序。",
        "auto_codex_rotation": "自动切换 Codex 账号",
        "auto_codex_rotation_subtitle": "当前 Codex 账号 5 小时额度偏低时，自动切换到最佳可用账号。",
        "codex_rotation_threshold": "低于此值切换",
        "codex_rotation_threshold_subtitle": "触发自动切换的 5 小时剩余额度。",
        "use_account": "使用此账号",
        "login_account": "登录",
        "remove_account": "移除账号",
        "remove_account_confirmation": "从 AgentBar 和本机 Codex 凭据中移除此账号。之后仍可重新登录添加。",
        "switching_account": "正在切换账号",
        "daily_usage_for": "每日用量",
        "software_update": "软件更新",
        "current_version": "当前版本",
        "check_for_updates": "检查更新",
        "install_and_restart": "安装并重启",
        "updates_daily_check": "AgentBar 每天会自动检查一次更新。",
        "checking_for_updates": "正在检查 GitHub Releases...",
        "app_up_to_date": "AgentBar 已是最新版本。",
        "downloading_update": "正在下载 %@...",
        "update_ready_to_install": "%@ 已下载，可以安装。",
        "installing_update": "正在安装 %@ 并重启...",
        "update_check_failed": "更新失败：%@",
        "update_install_subtitle": "将已下载的更新安装到 /Applications。",
        "title": "Codex 用量审计",
        "subtitle": "读取本机 JSONL，定位 token 与额度去向。",
        "visible_calls": "可见调用",
        "cached_input": "缓存输入",
        "uncached_input": "未缓存输入",
        "reasoning_output": "推理输出",
        "estimated_cost": "估算成本",
        "model_calls": "模型调用",
        "threads": "线程",
        "calls": "调用",
        "calls_caption": "显示当前筛选范围内的模型调用。点击任意行查看来源和 token 构成。",
        "threads_caption": "按线程聚合调用。点击线程展开其调用。",
        "time": "时间",
        "thread": "线程",
        "duration": "时长",
        "initiated": "发起",
        "model": "模型",
        "effort": "Effort",
        "cached": "缓存",
        "uncached": "未缓存",
        "output": "输出",
        "reasoning": "推理",
        "unknown_thread": "未知线程",
        "call_investigator": "调用详情",
        "show_source": "显示来源",
        "last_call_input": "本次输入",
        "exact_from_callback": "来自 token callback",
        "fresh_context": "新上下文",
        "assistant_output": "助手输出",
        "configured_price": "按当前价格表估算",
        "source_line": "来源行",
        "source_file_line": "源文件和行号",
        "privacy_note": "导出保存聚合字段和派生线程标题，不保存完整 prompt、回复或工具输出。",
        "exported": "已导出",
        "export_failed": "导出失败：",
        "page": "页",
        "budgets": "预算",
        "budget_subtitle": "为日/周 Token 和费用设置软阈值，超出时菜单栏提示。",
        "daily_token_budget": "每日 Token 预算",
        "weekly_token_budget": "每周 Token 预算",
        "daily_cost_budget": "每日费用预算",
        "weekly_cost_budget": "每周费用预算",
        "daily_token_budget_subtitle": "0 表示关闭每日 Token 提醒。",
        "weekly_token_budget_subtitle": "0 表示关闭每周 Token 提醒。",
        "daily_cost_budget_subtitle": "0 表示关闭每日费用提醒。",
        "weekly_cost_budget_subtitle": "0 表示关闭每周费用提醒。",
        "data_source_health": "数据源健康",
        "top_usage": "高消耗定位",
        "session_drilldown": "会话明细",
        "year_activity": "年度活动",
        "account_health": "账号健康",
        "account_health_subtitle": "集中处理重新登录、数据源异常和无效账号。",
        "quota_capacity_history": "额度容量估算",
        "quota_capacity_frequency": "额度容量采样频率",
        "quota_capacity_frequency_subtitle": "按此间隔记录 5H/本周额度推算历史。",
        "quota_capacity_history_tooltip": "根据最近采样估算 5H 和本周额度窗口的总 Token 容量，用来观察容量变化趋势并判断当前使用节奏。",
        "use_it_or_lose_it": "用掉，否则失效",
        "expires_today_message": "有一张储备重置今天过期。如有重要任务排队，建议过期前使用。",
        "expiry_warning": "过期提醒",
        "waiting_on_meters": "等待额度数据",
        "waiting_on_meters_message": "已看到重置储备，但 Codex 用量窗口还没加载。",
        "refresh_after_sign_in": "Codex 登录后刷新",
        "no_reset_cushion": "没有重置缓冲",
        "no_reset_cushion_message": "当前没有可用储备重置，请留意本周额度。",
        "let_5h_refill": "等 5 小时额度恢复",
        "let_5h_refill_message": "本周余量还可以，短窗口也快恢复，先保留重置。",
        "deadline_call": "按截止期限判断",
        "deadline_call_message": "短窗口紧张但本周余量充足；只有真实工作被挡住时才用重置。",
        "five_hour_nearly_empty": "5 小时额度将尽",
        "go_burn_tokens": "可以消耗一些额度",
        "go_burn_tokens_message": "你有储备重置，本周额度偏低，距离刷新还有几天。",
        "green_light_with_brakes": "可以用，但别浪费",
        "green_light_with_brakes_message": "如果 Codex 阻塞真实工作，使用重置是合理的；不要只为清空仪表而消耗。",
        "hold_that_reset": "保留这次重置",
        "hold_that_reset_message": "本周余量健康，下次刷新也比较近。",
        "cruise_mode": "正常使用",
        "cruise_mode_message": "继续工作。大批量运行前再检查一次。",
        "most_constrained": "最紧张",
        "lowest_5h": "最低 5 小时",
        "lowest_weekly": "最低本周",
        "quota_pressure": "额度压力",
        "view_details": "查看详情",
        "view_all_services": "查看全部服务",
        "view_all_models": "查看全部模型",
        "best_account": "推荐账号",
        "five_hour_exhausts": "预计 5 小时额度耗尽于",
        "five_hour_healthy": "5 小时额度暂无风险",
        "rotation_ready": "自动轮换会触发",
        "rotation_standby": "自动轮换待命",
        "quota_details": "额度详情",
        "active_account": "当前账号",
        "recommended_account": "推荐账号",
        "rotation": "自动轮换",
        "will_trigger": "会触发",
        "standby": "待命",
        "not_projected": "暂无预计耗尽时间",
        "quota_eta": "额度 ETA",
        "now": "现在",
        "samples": "样本",
        "waiting": "等待至少两次同一额度窗口内的采样和 token 消耗后生成估算。",
        "sample_usage": "样本消耗",
        "rapid_burn": "快速消耗提醒",
        "sessions": "会话",
        "projects": "项目",
        "days": "日期",
        "models": "模型",
        "latest": "最新",
        "select_session": "选择一个高消耗会话查看模型分布。",
        "unknown_project": "未知项目",
        "healthy": "账号和数据源暂无需要处理的问题。",
        "login": "登录",
        "remove": "删除账号",
        "usage_anomalies": "用量异常",
        "week": "本周",
        "no_sources": "暂无数据源状态",
        "live": "正常",
        "issues": "问题",
        "yes": "是",
        "no": "否"
    ]
}
