import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case english
    case chinese

    var id: String { rawValue }

    var title: String {
        switch self {
        case .english: "English"
        case .chinese: "中文"
        }
    }
}

enum L {
    static func text(_ key: String, _ language: AppLanguage) -> String {
        switch language {
        case .english:
            english[key] ?? key
        case .chinese:
            chinese[key] ?? english[key] ?? key
        }
    }

    private static let english: [String: String] = [
        "overview": "Overview",
        "statistics": "Statistics",
        "settings": "Settings",
        "refresh": "Refresh",
        "show_hud": "Show HUD",
        "hide_hud": "Hide HUD",
        "five_hour": "5-hour",
        "weekly": "Weekly",
        "remaining": "remaining",
        "tokens": "Tokens",
        "cost": "Cost",
        "service_mix": "Service mix",
        "model_detail": "Model detail",
        "range": "Range",
        "data_sources": "Data sources",
        "security": "Security",
        "refresh_interval": "Refresh interval",
        "login_item": "Open at login",
        "menu_item": "Menu bar item",
        "language": "Language",
        "active_account_windows": "Current account 5H/WK",
        "lowest_remaining": "Lowest remaining",
        "total_tokens": "Total tokens",
        "codex_only": "Codex remaining",
        "custom_range": "Custom range",
        "empty_cost": "Cost requires model pricing or an authorized Admin API source.",
        "claude_unavailable": "Claude Code source unavailable",
        "usage_statistics": "Usage",
        "service": "Service",
        "all": "All",
        "openai": "OpenAI",
        "anthropic": "Anthropic",
        "view": "View",
        "timeline": "Timeline",
        "details": "Details",
        "total_cost": "Total cost",
        "daily_usage": "Daily usage",
        "current_limits": "Current limits",
        "by_service": "By service",
        "by_model": "By model",
        "no_usage_events": "No usage events",
        "no_usage_data": "No usage data",
        "no_quota_windows": "No quota windows",
        "no_model_data": "No model data",
        "loading_accounts": "Loading accounts",
        "loading_account_info": "Loading account information",
        "loading_account_info_subtitle": "Reading local Codex and Claude Code accounts",
        "refreshing_accounts": "Refreshing accounts",
        "refreshing": "Refreshing",
        "accounts_loaded": "accounts loaded",
        "share": "share",
        "input_abbrev": "In",
        "output_abbrev": "Out",
        "reset_time_unknown": "Reset time unknown",
        "resets_after": "until reset",
        "accounts": "Accounts",
        "accounts_settings_subtitle": "Automatically detects local accounts; no placeholder is shown without a safe data source.",
        "available": "Available",
        "no_safe_local_source": "No safe local source",
        "menu_bar": "Menu bar",
        "menu_bar_settings_subtitle": "Control what the menu bar status item displays.",
        "display_value": "Display value",
        "display_value_subtitle": "Choose the value next to the icon.",
        "refresh_settings_subtitle": "Background polling interval for read-only local usage sync.",
        "refresh_interval_subtitle": "Applies to local read-only data sync.",
        "open_at_login_subtitle": "Open AgentBar at login.",
        "general": "General",
        "general_settings_subtitle": "Language and app behavior.",
        "language_subtitle": "Interface language.",
        "current_account": "Current account",
        "current": "Current",
        "no_cost_data": "No cost data",
        "usage_windows": "Usage windows",
        "team": "Team"
        ,"login_accounts": "Login accounts",
        "login_accounts_subtitle": "Open the provider CLI login flow in Terminal, then refresh AgentBar.",
        "login_codex": "Login Codex",
        "login_claude": "Login Claude",
        "theme_color": "Theme color",
        "theme_color_subtitle": "Applies to selections, charts, bars, and quota progress.",
        "account_sort": "Account sorting",
        "account_sort_subtitle": "Controls account order in the popover and current limits.",
        "use_account": "Use account",
        "switching_account": "Switching account",
        "daily_usage_for": "Daily usage"
    ]

    private static let chinese: [String: String] = [
        "overview": "概览",
        "statistics": "统计",
        "settings": "设置",
        "refresh": "刷新",
        "show_hud": "显示 HUD",
        "hide_hud": "隐藏 HUD",
        "five_hour": "5 小时",
        "weekly": "本周",
        "remaining": "剩余",
        "tokens": "Token",
        "cost": "费用",
        "service_mix": "服务占比",
        "model_detail": "模型明细",
        "range": "范围",
        "data_sources": "数据源",
        "security": "安全",
        "refresh_interval": "刷新间隔",
        "login_item": "开机启动",
        "menu_item": "菜单栏显示",
        "language": "语言",
        "active_account_windows": "当前账号 5 小时/本周",
        "lowest_remaining": "最低剩余额度",
        "total_tokens": "总 Token",
        "codex_only": "Codex 剩余",
        "custom_range": "自定义范围",
        "empty_cost": "费用需要模型价格或授权的 Admin API 数据源。",
        "claude_unavailable": "Claude Code 数据源不可用",
        "usage_statistics": "用量统计",
        "service": "服务",
        "all": "全部",
        "openai": "OpenAI",
        "anthropic": "Anthropic",
        "view": "视图",
        "timeline": "时间线",
        "details": "明细",
        "total_cost": "总花费",
        "daily_usage": "每日用量",
        "current_limits": "当前限额",
        "by_service": "按服务",
        "by_model": "按模型",
        "no_usage_events": "暂无用量事件",
        "no_usage_data": "暂无用量数据",
        "no_quota_windows": "暂无限额窗口",
        "no_model_data": "暂无模型数据",
        "loading_accounts": "正在加载账号",
        "loading_account_info": "正在加载账号信息",
        "loading_account_info_subtitle": "正在只读同步本机 Codex 与 Claude Code 账号",
        "refreshing_accounts": "正在刷新账号",
        "refreshing": "正在刷新",
        "accounts_loaded": "个账号已载入",
        "share": "占比",
        "input_abbrev": "入",
        "output_abbrev": "出",
        "reset_time_unknown": "重置时间未知",
        "resets_after": "后重置",
        "accounts": "账号",
        "accounts_settings_subtitle": "自动检测本机账号；无安全数据源时不显示占位账号。",
        "available": "可用",
        "no_safe_local_source": "无安全本地数据源",
        "menu_bar": "菜单栏",
        "menu_bar_settings_subtitle": "控制菜单栏状态项显示。",
        "display_value": "显示内容",
        "display_value_subtitle": "选择图标旁显示的数值。",
        "refresh_settings_subtitle": "后台只读同步用量的轮询频率。",
        "refresh_interval_subtitle": "应用于本地只读数据同步。",
        "open_at_login_subtitle": "登录时打开 AgentBar。",
        "general": "通用",
        "general_settings_subtitle": "语言和应用行为。",
        "language_subtitle": "界面语言。",
        "current_account": "当前账号",
        "current": "当前",
        "no_cost_data": "暂无费用数据",
        "usage_windows": "用量窗口",
        "team": "团队",
        "login_accounts": "登录账号",
        "login_accounts_subtitle": "在终端打开服务商 CLI 登录流程，然后刷新 AgentBar。",
        "login_codex": "登录 Codex",
        "login_claude": "登录 Claude",
        "theme_color": "主题色",
        "theme_color_subtitle": "应用到选中态、图表、柱状图和额度进度。",
        "account_sort": "账号排序",
        "account_sort_subtitle": "控制下拉菜单和当前限额里的账号顺序。",
        "use_account": "使用此账号",
        "switching_account": "正在切换账号",
        "daily_usage_for": "每日用量"
    ]
}
