import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case english
    case chinese

    var id: String { rawValue }

    var title: String {
        switch self {
        case .english: "English"
        case .chinese: "中文"
        }
    }
}

enum L {
    static func text(_ key: String, _ language: AppLanguage) -> String {
        switch language {
        case .english:
            english[key] ?? key
        case .chinese:
            chinese[key] ?? english[key] ?? key
        }
    }

    private static let english: [String: String] = [
        "overview": "Overview",
        "statistics": "Statistics",
        "settings": "Settings",
        "quit_app": "Quit",
        "refresh": "Refresh",
        "five_hour": "5-hour",
        "weekly": "Weekly",
        "remaining": "remaining",
        "tokens": "Tokens",
        "cost": "Cost",
        "service_mix": "Service mix",
        "model_detail": "Model detail",
        "range": "Range",
        "data_sources": "Data sources",
        "security": "Security",
        "refresh_interval": "Refresh interval",
        "interval": "Interval:",
        "login_item": "Open at login",
        "menu_item": "Menu bar item",
        "language": "Language",
        "active_account_windows": "Current account 5H/WK",
        "lowest_remaining": "Lowest remaining",
        "total_tokens": "Total tokens",
        "codex_only": "Codex remaining",
        "custom_range": "Custom range",
        "empty_cost": "Cost requires model pricing or an authorized Admin API source.",
        "claude_unavailable": "Claude Code source unavailable",
        "usage_statistics": "Usage",
        "service": "Service",
        "all": "All",
        "openai": "OpenAI",
        "anthropic": "Anthropic",
        "view": "View",
        "timeline": "Timeline",
        "details": "Details",
        "total_cost": "Total cost",
        "total": "Total",
        "daily_usage": "Daily usage",
        "current_limits": "Current limits",
        "by_service": "By service",
        "by_model": "By model",
        "no_usage_events": "No usage events",
        "no_usage_data": "No usage data",
        "no_quota_windows": "No quota windows",
        "no_model_data": "No model data",
        "loading_accounts": "Loading accounts",
        "loading_account_info": "Loading account information",
        "loading_account_info_subtitle": "Reading local Codex and Claude Code accounts",
        "accounts_loaded": "accounts loaded",
        "share": "share",
        "input_abbrev": "In",
        "output_abbrev": "Out",
        "reset_time_unknown": "Reset time unknown",
        "reset": "Reset",
        "reset_available": "reset available",
        "resets_available": "resets available",
        "expires": "expires",
        "resets_after": "until reset",
        "last_activity": "Last activity",
        "account_type": "Account type",
        "accounts": "Accounts",
        "accounts_settings_subtitle": "Automatically detects local accounts; no placeholder is shown without a safe data source.",
        "available": "Available",
        "no_safe_local_source": "No safe local source",
        "menu_bar": "Menu bar",
        "menu_bar_settings_subtitle": "Control what the menu bar status item displays.",
        "display_value": "Display value",
        "display_value_subtitle": "Choose the value next to the icon.",
        "refresh_settings_subtitle": "Background polling checks the Codex usage API, then reads local usage data.",
        "refresh_interval_subtitle": "Applies to Codex usage API sync and local data refresh.",
        "open_at_login_subtitle": "Open AgentBar at login.",
        "general": "General",
        "general_settings_subtitle": "Language and app behavior.",
        "language_subtitle": "Interface language.",
        "current_account": "Current account",
        "current": "Current",
        "account_forced_logout_warning": "OpenAI returned 401. Log in to this account again.",
        "account_unreadable_reset_warning": "Reset data is unreadable. Log in to this account again.",
        "no_cost_data": "No cost data",
        "usage_windows": "Usage windows",
        "team": "Team"
        ,"login_accounts": "Login accounts",
        "login_accounts_subtitle": "Open the provider CLI login flow in Terminal, then refresh AgentBar.",
        "login_codex": "Login Codex",
        "login_claude": "Login Claude",
        "dark_theme": "Dark theme",
        "dark_theme_subtitle": "Use a dark app appearance instead of following the system.",
        "tone_color": "Tone color",
        "tone_color_subtitle": "Applies to selections, charts, bars, and quota progress.",
        "account_sort": "Account sorting",
        "account_sort_subtitle": "Controls account order in the popover and current limits.",
        "auto_codex_rotation": "Auto-switch Codex accounts",
        "auto_codex_rotation_subtitle": "When the current Codex account is low on 5-hour quota, switch to the best available account.",
        "codex_rotation_threshold": "Switch below",
        "codex_rotation_threshold_subtitle": "Remaining 5-hour quota that triggers automatic switching.",
        "use_account": "Use account",
        "login_account": "Log in",
        "switching_account": "Switching account",
        "daily_usage_for": "Daily usage",
        "software_update": "Software update",
        "current_version": "Current version",
        "check_for_updates": "Check for updates",
        "install_and_restart": "Install and restart",
        "updates_daily_check": "AgentBar checks for updates automatically once per day.",
        "checking_for_updates": "Checking GitHub releases...",
        "app_up_to_date": "AgentBar is up to date.",
        "downloading_update": "Downloading %@...",
        "update_ready_to_install": "%@ is downloaded and ready to install.",
        "installing_update": "Installing %@ and restarting...",
        "update_check_failed": "Update failed: %@",
        "update_install_subtitle": "Install the downloaded update into /Applications."
    ]

    private static let chinese: [String: String] = [
        "overview": "概览",
        "statistics": "统计",
        "settings": "设置",
        "quit_app": "退出",
        "refresh": "刷新",
        "five_hour": "5 小时",
        "weekly": "本周",
        "remaining": "剩余",
        "tokens": "Token",
        "cost": "费用",
        "service_mix": "服务占比",
        "model_detail": "模型明细",
        "range": "范围",
        "data_sources": "数据源",
        "security": "安全",
        "refresh_interval": "刷新间隔",
        "interval": "区间：",
        "login_item": "开机启动",
        "menu_item": "菜单栏显示",
        "language": "语言",
        "active_account_windows": "当前账号 5 小时/本周",
        "lowest_remaining": "最低剩余额度",
        "total_tokens": "总 Token",
        "codex_only": "Codex 剩余",
        "custom_range": "自定义范围",
        "empty_cost": "费用需要模型价格或授权的 Admin API 数据源。",
        "claude_unavailable": "Claude Code 数据源不可用",
        "usage_statistics": "用量统计",
        "service": "服务",
        "all": "全部",
        "openai": "OpenAI",
        "anthropic": "Anthropic",
        "view": "视图",
        "timeline": "时间线",
        "details": "明细",
        "total_cost": "总花费",
        "total": "总计",
        "daily_usage": "每日用量",
        "current_limits": "当前限额",
        "by_service": "按服务",
        "by_model": "按模型",
        "no_usage_events": "暂无用量事件",
        "no_usage_data": "暂无用量数据",
        "no_quota_windows": "暂无限额窗口",
        "no_model_data": "暂无模型数据",
        "loading_accounts": "正在加载账号",
        "loading_account_info": "正在加载账号信息",
        "loading_account_info_subtitle": "正在只读同步本机 Codex 与 Claude Code 账号",
        "accounts_loaded": "个账号已载入",
        "share": "占比",
        "input_abbrev": "入",
        "output_abbrev": "出",
        "reset_time_unknown": "重置时间未知",
        "reset": "重置",
        "reset_available": "次重置可用",
        "resets_available": "次重置可用",
        "expires": "过期",
        "resets_after": "后重置",
        "last_activity": "最近活动",
        "account_type": "账号类型",
        "accounts": "账号",
        "accounts_settings_subtitle": "自动检测本机账号；无安全数据源时不显示占位账号。",
        "available": "可用",
        "no_safe_local_source": "无安全本地数据源",
        "menu_bar": "菜单栏",
        "menu_bar_settings_subtitle": "控制菜单栏状态项显示。",
        "display_value": "显示内容",
        "display_value_subtitle": "选择图标旁显示的数值。",
        "refresh_settings_subtitle": "后台轮询会先检查 Codex 用量 API，再读取本地用量数据。",
        "refresh_interval_subtitle": "应用于 Codex 用量 API 同步和本地数据刷新。",
        "open_at_login_subtitle": "登录时打开 AgentBar。",
        "general": "通用",
        "general_settings_subtitle": "语言和应用行为。",
        "language_subtitle": "界面语言。",
        "current_account": "当前账号",
        "current": "当前",
        "account_forced_logout_warning": "OpenAI 返回 401，请重新登录此账号。",
        "account_unreadable_reset_warning": "重置数据不可读，请重新登录此账号。",
        "no_cost_data": "暂无费用数据",
        "usage_windows": "用量窗口",
        "team": "团队",
        "login_accounts": "登录账号",
        "login_accounts_subtitle": "在终端打开服务商 CLI 登录流程，然后刷新 AgentBar。",
        "login_codex": "登录 Codex",
        "login_claude": "登录 Claude",
        "dark_theme": "深色主题",
        "dark_theme_subtitle": "使用深色应用外观，而不是跟随系统。",
        "tone_color": "色调颜色",
        "tone_color_subtitle": "应用到选中态、图表、柱状图和额度进度。",
        "account_sort": "账号排序",
        "account_sort_subtitle": "控制下拉菜单和当前限额里的账号顺序。",
        "auto_codex_rotation": "自动切换 Codex 账号",
        "auto_codex_rotation_subtitle": "当前 Codex 账号 5 小时额度偏低时，自动切换到最佳可用账号。",
        "codex_rotation_threshold": "低于此值切换",
        "codex_rotation_threshold_subtitle": "触发自动切换的 5 小时剩余额度。",
        "use_account": "使用此账号",
        "login_account": "登录",
        "switching_account": "正在切换账号",
        "daily_usage_for": "每日用量",
        "software_update": "软件更新",
        "current_version": "当前版本",
        "check_for_updates": "检查更新",
        "install_and_restart": "安装并重启",
        "updates_daily_check": "AgentBar 每天会自动检查一次更新。",
        "checking_for_updates": "正在检查 GitHub Releases...",
        "app_up_to_date": "AgentBar 已是最新版本。",
        "downloading_update": "正在下载 %@...",
        "update_ready_to_install": "%@ 已下载，可以安装。",
        "installing_update": "正在安装 %@ 并重启...",
        "update_check_failed": "更新失败：%@",
        "update_install_subtitle": "将已下载的更新安装到 /Applications。"
    ]
}
